version: '3.8'

services:
  news-app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    environment:
      - PORT=3001
    restart: unless-stopped